development:
  adapter: postgresql
  encoding: unicode
  database: wercker_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wercker_test
  pool: 5
  username: postgres
